### ISSUE TITLE
.DS_Store 文件过滤

### ISSUE THREAD

**Issue by dongchongle** [bluedazzle/hellspawn-hunter-weapp#1]
在掘金上看见文章过来的。

.DS_Store 可以过滤（禁止）下。

`defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool TRUE`

这条命令可以禁止生成 .DS_Store 文件；

或者配置下 .gitignore 文件把它过滤掉。

当然其实也没什么影响，只是保持仓库整洁。233

（还有，体验了下，不错的小程序感谢～）

**Comment by bluedazzle** [comment]
谢谢建议！

已经删掉 .DS_Store 文件
